### ISSUE TITLE
Can't ping on Ubuntu 24.04

### ISSUE THREAD

**Issue by github2452** [lo2dev/Echo#2]
whatever site/address I type the window gets stuck/freeze with Pinging (after I press the Ping button)
I'm using Ubuntu 24.04

**Comment by lo2dev** [comment]
Hi, can you please run `flatpak run io.github.lo2dev.Echo` in a terminal and post the output if there is any?

**Comment by lo2dev** [comment]
It seems to be an issue (specifically on Ubuntu 24.04) with the library I'm using that makes it possible to ping. I'm afraid there's not much I can do as the app dev until this gets fixed in the library.

There is a workaround that fixes this if you're comfortable with terminal usage on [this page](https://github.com/ValentinBELYN/icmplib/blob/main/docs/6-use-icmplib-without-privileges.md) on step 2.
